## 02 — Data Cleaning and Quality Control

In [ ]:
### Filter eye movements and apply fixation-duration criteria

In [189]:
import pandas as pd
from pathlib import Path

In [191]:
#Get the main project folder
project_folder = Path.cwd().parent

In [264]:
# Construct the correct path to the interim folder and load it explicitly
csv_file_path = project_folder / "data" / "interim" / "raw_data_selected_01.csv" 
raw_data_selected_01 = pd.read_csv(csv_file_path)

In [197]:
raw_data_selected_01.shape # This means 504,047 rows and 12 columns.

(504047, 12)

In [199]:
print(type(raw_data_selected_01))
raw_data_selected_01.info()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504047 entries, 0 to 504046
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Participant name         504047 non-null  object
 1   Presented Media name     502751 non-null  object
 2   Timeline name            504047 non-null  object
 3   Recording timestamp  ms  504047 non-null  int64
 4   time_diff                504047 non-null  int64
 5   Gaze event duration  ms  504047 non-null  int64
 6   Validity left            502751 non-null  object
 7   Validity right           502751 non-null  object
 8   Eye movement type        504047 non-null  object
 9   Gaze point X  DACS px    468949 non-null  float64
 10  Gaze point Y  DACS px    468949 non-null  float64
 11  AOIs                     194094 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 46.1+ MB

In [201]:
raw_data_selected_01.head() # Inspect the first observations to verify the imported data.

,Participant name,Presented Media name,Timeline name,Recording timestamp ms,time_diff,Gaze event duration ms,Validity left,Validity right,Eye movement type,Gaze point X DACS px,Gaze point Y DACS px,AOIs
0,part05,NaN,List2,139892,0,225,NaN,NaN,Fixation,NaN,NaN,left
1,part05,NaN,List2,139892,0,225,NaN,NaN,Fixation,NaN,NaN,left
2,part05,Item12c.avi,List2,139899,0,225,Valid,Valid,Fixation,477.0,442.0,left
3,part05,Item12c.avi,List2,139907,8,225,Valid,Valid,Fixation,482.0,437.0,left
4,part05,Item12c.avi,List2,139915,16,225,Valid,Valid,Fixation,476.0,435.0,left

In [203]:
raw_data_selected_01.columns.tolist() 
# Inspection. It lets you print out the names so you can visually check them.

['Participant name',
 'Presented Media name',
 'Timeline name',
 'Recording timestamp  ms',
 'time_diff',
 'Gaze event duration  ms',
 'Validity left',
 'Validity right',
 'Eye movement type',
 'Gaze point X  DACS px',
 'Gaze point Y  DACS px',
 'AOIs']

In [205]:
# Inspect column data types to verify the structure of the selected dataset
# and identify variables relevant to the subsequent analysis.
raw_data_selected_01.dtypes

Participant name            object
Presented Media name        object
Timeline name               object
Recording timestamp  ms      int64
time_diff                    int64
Gaze event duration  ms      int64
Validity left               object
Validity right              object
Eye movement type           object
Gaze point X  DACS px      float64
Gaze point Y  DACS px      float64
AOIs                        object
dtype: object

In [207]:
# Assess missing values in the selected dataset to evaluate data completeness.
# Missing gaze coordinates (Gaze point X and Gaze point Y) are expected in
# eye-tracking data when gaze cannot be reliably recorded.
# Missing Area of Interest (AOI) labels indicate that a gaze sample was not
# assigned to a predefined target area. These patterns will be examined
# before further data processing and analysis.
raw_data_selected_01.isna().sum()

Participant name                0
Presented Media name         1296
Timeline name                   0
Recording timestamp  ms         0
time_diff                       0
Gaze event duration  ms         0
Validity left                1296
Validity right               1296
Eye movement type               0
Gaze point X  DACS px       35098
Gaze point Y  DACS px       35098
AOIs                       309953
dtype: int64

In [209]:
# Identify columns containing missing values and rank them by the number
# of missing entries to support data quality assessment and preprocessing.

missing = raw_data_selected_01.isna().sum()

missing[missing > 0].sort_values(ascending=False)

AOIs                     309953
Gaze point X  DACS px     35098
Gaze point Y  DACS px     35098
Presented Media name       1296
Validity left              1296
Validity right             1296
dtype: int64

In [211]:
raw_data_selected_01.describe()

,Recording timestamp ms,time_diff,Gaze event duration ms,Gaze point X DACS px,Gaze point Y DACS px
count,504047.000000,504047.000000,504047.000000,468949.000000,468949.000000
mean,420546.733533,7301.899864,398.629900,951.378282,563.305920
std,174316.695867,16873.115413,499.382687,412.888890,146.704188
min,73162.000000,0.000000,8.000000,-2277.000000,-1036.000000
25%,276160.500000,3275.000000,133.000000,550.000000,479.000000
50%,423168.000000,6558.000000,250.000000,958.000000,550.000000
75%,567045.000000,9842.000000,450.000000,1174.000000,630.000000
max,805558.000000,602612.000000,4392.000000,3096.000000,1828.000000

In [213]:
# Summarize numeric and categorical variables. 
raw_data_selected_01.describe(include="all")

,Participant name,Presented Media name,Timeline name,Recording timestamp ms,time_diff,Gaze event duration ms,Validity left,Validity right,Eye movement type,Gaze point X DACS px,Gaze point Y DACS px,AOIs
count,504047,502751,504047,504047.000000,504047.000000,504047.000000,502751,502751,504047,468949.000000,468949.000000,194094
unique,16,80,4,NaN,NaN,NaN,2,2,4,NaN,NaN,2
top,part34,Item16b.avi,List4,NaN,NaN,NaN,Valid,Valid,Fixation,NaN,NaN,left
freq,31945,11278,188671,NaN,NaN,NaN,452290,455113,386924,NaN,NaN,104109
mean,NaN,NaN,NaN,420546.733533,7301.899864,398.629900,NaN,NaN,NaN,951.378282,563.305920,NaN
std,NaN,NaN,NaN,174316.695867,16873.115413,499.382687,NaN,NaN,NaN,412.888890,146.704188,NaN
min,NaN,NaN,NaN,73162.000000,0.000000,8.000000,NaN,NaN,NaN,-2277.000000,-1036.000000,NaN
25%,NaN,NaN,NaN,276160.500000,3275.000000,133.000000,NaN,NaN,NaN,550.000000,479.000000,NaN
50%,NaN,NaN,NaN,423168.000000,6558.000000,250.000000,NaN,NaN,NaN,958.000000,550.000000,NaN
75%,NaN,NaN,NaN,567045.000000,9842.000000,450.000000,NaN,NaN,NaN,1174.000000,630.000000,NaN
max,NaN,NaN,NaN,805558.000000,602612.000000,4392.000000,NaN,NaN,NaN,3096.000000,1828.000000,NaN

In [215]:
# Generate a structured overview of the selected dataset to assess its
# schema, variable types, and data completeness before further analysis.

print("\nColumns:")
print(raw_data_selected_01.columns.tolist())
#Prints all your column names neatly as a Python list so you can easily read them or copy/paste them.

print("\nData types:")
print(raw_data_selected_01.dtypes)
#Prints the data type (text, number, etc.) of every column.

print("\nMissing values:")
print(raw_data_selected_01.isna().sum().sort_values(ascending=False))
#Counts the missing values for each column and sorts them from highest to lowest.

# Quantify missing values per column, ordered from highest to lowest.

Columns:
['Participant name', 'Presented Media name', 'Timeline name', 'Recording timestamp  ms', 'time_diff', 'Gaze event duration  ms', 'Validity left', 'Validity right', 'Eye movement type', 'Gaze point X  DACS px', 'Gaze point Y  DACS px', 'AOIs']

Data types:
Participant name            object
Presented Media name        object
Timeline name               object
Recording timestamp  ms      int64
time_diff                    int64
Gaze event duration  ms      int64
Validity left               object
Validity right              object
Eye movement type           object
Gaze point X  DACS px      float64
Gaze point Y  DACS px      float64
AOIs                        object
dtype: object

Missing values:
AOIs                       309953
Gaze point X  DACS px       35098
Gaze point Y  DACS px       35098
Presented Media name         1296
Validity left                1296
Validity right               1296
Participant name                0
Timeline name                   0
Recording timestamp  ms         0
Gaze event duration  ms         0
time_diff                       0
Eye movement type               0
dtype: int64

In [219]:
# Filter the dataset to retain valid fixation events with available participant
# and stimulus identifiers, excluding other eye-tracking events and incomplete records.
# This reduces noise and prepares the data for subsequent analysis.
raw_data_filtered= raw_data_selected_01[
    (raw_data_selected_01["Eye movement type"] == "Fixation") &
    (raw_data_selected_01["Participant name"].notna()) &
    (raw_data_selected_01["Presented Media name"].notna())
].copy()

print("Rows after filtering:", len(raw_data_filtered))

# The dataset was reduced from 504,047 to 385,898 rows,
# excluding approximately 23.44% of the original records.

Rows after filtering: 385898

In [221]:
#Standardize the column names
raw_data_filtered.columns

Index(['Participant name', 'Presented Media name', 'Timeline name',
       'Recording timestamp  ms', 'time_diff', 'Gaze event duration  ms',
       'Validity left', 'Validity right', 'Eye movement type',
       'Gaze point X  DACS px', 'Gaze point Y  DACS px', 'AOIs'],
      dtype='object')

In [223]:
#Check the fixation-duration distribution
raw_data_filtered["Gaze event duration  ms"].describe()

count    385898.000000
mean        485.505621
std         522.764561
min          67.000000
25%         208.000000
50%         308.000000
75%         533.000000
max        4392.000000
Name: Gaze event duration  ms, dtype: float64

In [225]:
# Count extreme long fixations (> 2000 ms) 
(raw_data_filtered["Gaze event duration  ms"] > 2000).sum()

10841

In [227]:
#and extrem short fixaitons (< 80 ms))
(raw_data_filtered["Gaze event duration  ms"] < 80).sum()

3547

In [229]:
# To remove the exterm shorter and longer fixatoins
results_filtered = raw_data_filtered[
    (raw_data_filtered["Gaze event duration  ms"] >= 80) &
    (raw_data_filtered
    ["Gaze event duration  ms"] <= 2000)
].copy()
# Create an independent copy of the filtered dataset for subsequent processing.

In [231]:
#Compare before 
raw_data_filtered["Gaze event duration  ms"].describe()
# how many rows were = 385898

count    385898.000000
mean        485.505621
std         522.764561
min          67.000000
25%         208.000000
50%         308.000000
75%         533.000000
max        4392.000000
Name: Gaze event duration  ms, dtype: float64

In [233]:
# and after see how many rows remain
results_filtered["Gaze event duration  ms"].describe()
# how many rows remaned = 371510

count    371510.000000
mean        422.641466
std         336.729144
min          83.000000
25%         208.000000
50%         308.000000
75%         508.000000
max        1992.000000
Name: Gaze event duration  ms, dtype: float64

In [235]:
retained_percentage = (
    len(results_filtered) / len(raw_data_filtered) * 100
)
print(f"{retained_percentage:.2f}% of the data were retained.")
# DA. 96.27% of the data were retained.

96.27% of the data were retained.

In [237]:
removed_percentage = 100 - retained_percentage

print(f"{removed_percentage:.2f}% of the data were removed.")

# 3.73% of the data were removed - the extrem long and shorter fixations.

3.73% of the data were removed.

In [239]:
total_rows = len(raw_data_filtered)

short_fixations = (
    raw_data_filtered["Gaze event duration  ms"] < 80
).sum()

long_fixations = (
    raw_data_filtered["Gaze event duration  ms"] > 2000
).sum()

missing_duration = (
    raw_data_filtered["Gaze event duration  ms"].isna()
).sum()

results_filtered = raw_data_filtered[
    (raw_data_filtered["Gaze event duration  ms"] >= 80) &
    (raw_data_filtered  ["Gaze event duration  ms"] <= 2000)
].copy()

retained_rows = len(results_filtered)
removed_rows = total_rows - retained_rows

print(f"Original rows:       {total_rows:,}")
print(f"Short fixations:     {short_fixations:,}")
print(f"Long fixations:      {long_fixations:,}")
print(f"Missing duration:    {missing_duration:,}")
print(f"Rows retained:       {retained_rows:,}")
print(f"Rows removed:        {removed_rows:,}")
print(f"Retained:             {retained_rows / total_rows * 100:.2f}%")
print(f"Removed:              {removed_rows / total_rows * 100:.2f}%")

Original rows:       385,898
Short fixations:     3,547
Long fixations:      10,841
Missing duration:    0
Rows retained:       371,510
Rows removed:        14,388
Retained:             96.27%
Removed:              3.73%

In [241]:
print(results_filtered.columns.tolist())

['Participant name', 'Presented Media name', 'Timeline name', 'Recording timestamp  ms', 'time_diff', 'Gaze event duration  ms', 'Validity left', 'Validity right', 'Eye movement type', 'Gaze point X  DACS px', 'Gaze point Y  DACS px', 'AOIs']

In [243]:
results_binned = results_filtered.copy() #  Parentheses need to copy as the DataFrame.

In [245]:
# Calculate the onset of each stimulus/trial
results_binned["item_onset_time"] = (
    results_binned
    .groupby(["Participant name", "Presented Media name"])["Recording timestamp  ms"]
    .transform("min")
)

# Calculate time relative to stimulus onset
results_binned["ms"] = (
    results_binned["Recording timestamp  ms"]
    - results_binned["item_onset_time"]
)

print(results_binned[
    [
        "Participant name",
        "Presented Media name",
        "Recording timestamp  ms",
        "item_onset_time",
        "ms"
    ]
].head(10))

   Participant name Presented Media name  Recording timestamp  ms  \
2            part05          Item12c.avi                   139899
3            part05          Item12c.avi                   139907
4            part05          Item12c.avi                   139915
5            part05          Item12c.avi                   139924
6            part05          Item12c.avi                   139932
7            part05          Item12c.avi                   139940
8            part05          Item12c.avi                   139949
9            part05          Item12c.avi                   139957
10           part05          Item12c.avi                   139965
11           part05          Item12c.avi                   139974

    item_onset_time  ms
2            139899   0
3            139899   8
4            139899  16
5            139899  25
6            139899  33
7            139899  41
8            139899  50
9            139899  58
10           139899  66
11           139899  75

In [247]:
#Create the 20-ms bins
BIN_DURATION = 20

results_binned["bin20"] = (
    BIN_DURATION *
    (results_binned["ms"] / BIN_DURATION).round()
)

print(results_binned[
    ["ms", "bin20"]
].head(20))

     ms  bin20
2     0    0.0
3     8    0.0
4    16   20.0
5    25   20.0
6    33   40.0
7    41   40.0
8    50   40.0
9    58   60.0
10   66   60.0
11   75   80.0
12   83   80.0
13   91  100.0
14  100  100.0
15  108  100.0
16  116  120.0
17  125  120.0
18  133  140.0
24  183  180.0
25  191  200.0
26  200  200.0

In [249]:
#Rename the stimulus column
results_binned = results_binned.rename(
    columns={"Presented Media name": "items"}
)

In [251]:
# Strip '.avi' extension and surrounding spaces from entries in the 'items' column
results_binned["items"] = (
    results_binned["items"]
    .astype(str)
    .str.replace(".avi", "", regex=False)
    .str.strip()
)

In [253]:
print(results_binned.shape)
print(results_binned[
    [
        "Participant name",
        "items",
        "Recording timestamp  ms",
        "item_onset_time",
        "ms",
        "bin20"
    ]
].head(10))

(371510, 15)
   Participant name    items  Recording timestamp  ms  item_onset_time  ms  \
2            part05  Item12c                   139899           139899   0
3            part05  Item12c                   139907           139899   8
4            part05  Item12c                   139915           139899  16
5            part05  Item12c                   139924           139899  25
6            part05  Item12c                   139932           139899  33
7            part05  Item12c                   139940           139899  41
8            part05  Item12c                   139949           139899  50
9            part05  Item12c                   139957           139899  58
10           part05  Item12c                   139965           139899  66
11           part05  Item12c                   139974           139899  75

    bin20
2     0.0
3     0.0
4    20.0
5    20.0
6    40.0
7    40.0
8    40.0
9    60.0
10   60.0
11   80.0

In [255]:
# Rename columns in results_binned using pandas syntax
results_binned = results_binned.rename(
    columns={
        "Recording timestamp  ms": "RecordingTimestamp",
        "Participant name": "ParticipantName",
        "Presented Media name": "MediaName",
        "Eye movement type": "EyeMovementType",
        "Gaze point X  DACS px": "GazePointX",
        "Gaze point Y  DACS px": "GazePointY",
        "AOIs": "AOI",
        "Timeline name": "Lists",
        "Gaze event duration  ms": "GazeEventDur_ms",
    }
)

In [259]:
results_binned_02 = results_binned.copy()

In [261]:
# Inspect the updated column names
print(results_binned_02.columns.tolist())

['ParticipantName', 'items', 'Lists', 'RecordingTimestamp', 'time_diff', 'GazeEventDur_ms', 'Validity left', 'Validity right', 'EyeMovementType', 'GazePointX', 'GazePointY', 'AOI', 'item_onset_time', 'ms', 'bin20']

In [183]:
from pathlib import Path

# Save the transformed dataset to the interim data directory
# to preserve an intermediate analysis-ready version for subsequent steps.
interim_folder = project_folder / "data" / "interim"

csv_file_path = interim_folder / "results_binned_02.csv"
results_binned_02.to_csv(csv_file_path, index=False)

In [180]:
# End of the cleaning and transformation of the eye-tracking data. The next step is to analyze the data.